version: "3.8"

services:
  conj-ai:
    build: .
    container_name: conj-ai-service
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - OpenAI__Model=${OPENAI_MODEL}
      - OpenAI__Endpoint=${OPENAI_ENDPOINT}
      - OpenAI__ApiKey=${OPENAI_API_KEY}
    restart: unless-stopped
